export const ERROR_CODES = Object.freeze({
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_HTTP: 'NETWORK_HTTP',
  NETWORK_FETCH: 'NETWORK_FETCH',
  TIMETABLE_SOURCE_MISSING: 'TIMETABLE_SOURCE_MISSING',
  ANNOUNCEMENTS_LOAD_FAILED: 'ANNOUNCEMENTS_LOAD_FAILED',
  CALENDAR_LOAD_FAILED: 'CALENDAR_LOAD_FAILED',
  SW_REGISTER_FAILED: 'SW_REGISTER_FAILED'
});

export function createErrorInfo(code, message, context = {}) {
  return { code, message, context, at: new Date().toISOString() };
}
