name = "hgh-app-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_USER = "redaktion"

[[d1_databases]]
binding = "DB"
database_name = "hgh-app-db"
database_id = "7a6a1570-883f-4cf7-9989-34569a3a04eb"
migrations_dir = "../migrations"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "hgh-app-content"

[dev]
port = 8787
